name: event_booking_app_ui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  image_picker: ^1.0.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  country_icons: ^2.0.0

  # Updated Firebase packages to the latest stable versions
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  get: ^4.7.2
  awesome_dialog: ^3.2.1
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_svg: ^2.0.17
  flutter_local_notifications: ^19.1.0
  firebase_messaging: ^15.2.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/backgrounds/
    - assets/navigation/
