// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiHgsZ7HZ8PKWdNHbKyZNVcdWNRnm5pKc',
    appId: '1:393421467591:web:291ce7b992e1bc09fc33e2',
    messagingSenderId: '393421467591',
    projectId: 'event-hub-509cd',
    authDomain: 'event-hub-509cd.firebaseapp.com',
    storageBucket: 'event-hub-509cd.firebasestorage.app',
    measurementId: 'G-85PGG5H68G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGVV1Ij_lcX0yRBGd9pBM6bFSQq-VhFTI',
    appId: '1:393421467591:android:b66fa5a4801d3892fc33e2',
    messagingSenderId: '393421467591',
    projectId: 'event-hub-509cd',
    storageBucket: 'event-hub-509cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIJtrh29l8HG25wPIdT3-0W9H4qREKUW8',
    appId: '1:393421467591:ios:a57c5392ae149752fc33e2',
    messagingSenderId: '393421467591',
    projectId: 'event-hub-509cd',
    storageBucket: 'event-hub-509cd.firebasestorage.app',
    iosBundleId: 'com.example.eventBookingAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIJtrh29l8HG25wPIdT3-0W9H4qREKUW8',
    appId: '1:393421467591:ios:a57c5392ae149752fc33e2',
    messagingSenderId: '393421467591',
    projectId: 'event-hub-509cd',
    storageBucket: 'event-hub-509cd.firebasestorage.app',
    iosBundleId: 'com.example.eventBookingAppUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiHgsZ7HZ8PKWdNHbKyZNVcdWNRnm5pKc',
    appId: '1:393421467591:web:f03112586027e5bafc33e2',
    messagingSenderId: '393421467591',
    projectId: 'event-hub-509cd',
    authDomain: 'event-hub-509cd.firebaseapp.com',
    storageBucket: 'event-hub-509cd.firebasestorage.app',
    measurementId: 'G-GQ7Q4QFEFJ',
  );
}
